#+TITLE: MGF: Matt's Game Framework

MGF is a collision detection and physics library for use in 3D video games.

The library provides various features such as:

- structures to define shapes: ~Ray~, ~Segment~, ~AABB~, ~Rectangle~, ~Triangle~, ~Sphere~, ~Capsule~
- structures to define aggregate shapes: ~Mesh~, ~Compound~
- discrete collision detection: ~Overlaps~, ~Contains~
- continuous collision detection: ~Intersection~, ~Contact~, ~LocalContact~
- a bounding volume hierarchy: ~BVH~
- rigid body physics: ~RigidBody~, ~StaticBody~
- dynamic containers: ~Pool~

MGF is very much in its infancy and is therefore not feature complete. If you
notice any errors or poorly thought out interfaces be sure to let me know.

* MGF is 3D only

For the time being MGF is solely designed to handle 3D video games. This 
reflects my own use of MGF. If there is enough demand for MGF to support 2D
games, it may in the future.

* Contributing

MGF is welcome to anyone's work, and any part of the interface is open to 
discussion. Although if you are going to contribute new features please do 
be sure to include unit tests. 
